repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
            -   flake8-docstrings
            -   flake8-bugbear
            -   flake8-import-order
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
        -   id: black